### ISSUE TITLE
Re-export don't work with TypeDoc

### ISSUE THREAD

**Issue by Cloud2109** [sebastian-lenz/typedoc#100]
>1. import XXX = require('./lib/XXX');
>2.  
>3. export * from './lib/Properties';
>4.  
>5. export function create(): XXX.XXX {
>6.     return new XXX.XXX();
>7. }

Throw error:

*execute command line code:*
>typedoc --out ..\\..\XXX\XXX\public\XXX\ --mode modules --module commonjs --target ES5 --theme default --name XXX --hideGenerator .\

>>Using TypeScript 1.4.1 from C:\Users\XXX\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\bin
Error: C:/Users/XXX/Documents/Visual Studio 2013/Projects/XXX/XXX/app.ts(3)
 Declaration or statement expected.
Error: C:/Users/XXX/Documents/Visual Studio 2013/Projects/XXX/XXX/app.ts(3)
 Expression expected.
Error: C:/Users/XXX/Documents/Visual Studio 2013/Projects/XXX/XXX/app.ts(3)
 ';' expected.
Error: C:/Users/XXX/Documents/Visual Studio 2013/Projects/XXX/XXX/app.ts(3)
 Cannot find name 'from'.

**Comment by sebastian-lenz** [comment]
Exports like this are only supported with TypeScript 1.5. TypeDoc runs on TypeScript 1.4 and therefore cannot parse this kind of statement. Support for TypeScript 1.5 is in the making, see #95, it will be available after the official release of the new compiler. Exports like this are part of the new ES6 modules wich are a planned feature of an upcoming TypeDoc version, see #98.
