### ISSUE TITLE
Errors when creating documentation for my project

### ISSUE THREAD

**Issue by MatanBobi** [sebastian-lenz/typedoc#101]
Hey,
I was using typedoc (for typescript 0.9) and recently tried to upgrade to the latest version (I am using typescript 1.4.0).
As of the latest version, I keep getting errors (Compile errors) when im trying to run typedoc on my project.
Errors like: "Module ... Has no exported member ...", "Cannot find name "..." " And so on.
The documentation ofcourse isnt created.
Is it because I am using typescript 1.4 and not 1.4.1?
Thanks in advanced,
Matan.

**Comment by sebastian-lenz** [comment]
You should always use the TypeScript version bundled with TypeDoc, but as long as you install TypeDoc from npm and don't fiddle around the correct version should be installed and used when running TypDoc. 

I guess you are not passing all source files to TypeDoc. Did you make sure that you've supplied all source files like you pass them to the compiler?

Did you upgrade TypeDoc? Could you paste the outputs of TypeDoc?

**Comment by MatanBobi** [comment]
Hey sebastian,
Found out that my problem is with the d.ts files.
I couldnt find any example on how to exclude files from typedoc, Can you give me a refference to an example please?
Thanks.

**Comment by sebastian-lenz** [comment]
As long as you don't specify the option ```--includeDeclarations``` TypeDoc will not render declaration files. Also, if you receive compiler errors this won't help you. If you just pass a source path to TypeDoc you can exclude files using the ```--exclude``` option, the option expects a glob pattern. TypeDoc invokes the TypeScript compiler and fetches the internal generated compiler symbols, if the compiler fails you have either syntactic errors in your source files or you didn't pass the same options/files to TypeDoc as you did with TypeScript.

**Comment by MatanBobi** [comment]
Thanks sebastian, It was really my problem :+1:
