### ISSUE TITLE
Docs for callback parameters render incorrectly.

### ISSUE THREAD

**Issue by sccolbert** [sebastian-lenz/typedoc#102]
Here's the source comment for a particular function:
https://github.com/phosphorjs/phosphor/blob/HEAD/src/core/signaling.ts#L30

And here's the rendered docs:
https://phosphorjs.github.io/phosphor/modules/phosphor.core.html#connect

Notice that the documentation for the `method` callback is rendered incorrectly and causes the `Notes` and `Example` blocks to render in the wrong place and with the wrong indentation.

**Comment by sebastian-lenz** [comment]
Thanks for the report, I'll check into this.

**Comment by sebastian-lenz** [comment]
Hi Chris, it seems like the descriptions of your parameters have an additional indention caused by the minus symbols you use to separate the <code>@param</code> from the comments. As all contents of the comments are parsed as markdown this minus symbol causes markdown to generate an unordered list.

The <code>Notes</code> and <code>Examples</code> sections are appended to the last <code>Returns</code> block which is the correct behavior. Once you open a comment tag all following lines will be appended to that comment tag.

**Comment by sccolbert** [comment]
According to JSDoc, the hyphen is optional:

```
If you provide a description, you can make the JSDoc comment more readable by inserting a hyphen before the description. Be sure to include a space before and after the hyphen.
```

http://usejsdoc.org/tags-param.html

**Comment by sebastian-lenz** [comment]
Okay, thank you for the clarification. I've added a trim for trailing "-" in param comments.

**Comment by sccolbert** [comment]
Cheers!

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM containing the fix.

**Comment by sccolbert** [comment]
Many thanks!

**Comment by sccolbert** [comment]
This fix only appears to be working for methods, not functions:

Source:
![src](https://cloud.githubusercontent.com/assets/137289/9284019/5955905a-42a6-11e5-9738-9c4b33c31356.PNG)

Output:
![output](https://cloud.githubusercontent.com/assets/137289/9284022/5ef3b906-42a6-11e5-9570-98dcacdd6c1a.PNG)

**Comment by sebastian-lenz** [comment]
I think the output looks correct. TypeDoc lists all parameters in a list so the bullet in front of <code>obj:any</code> is intentional.

**Comment by sccolbert** [comment]
I meant that the `Notes` and `Examples` sections are indented under the `obj` parameter. In the source, those are separate sections which should be place after the auto-generated `return` and unindented.

I use this same comment style for methods, which generate correctly:
http://phosphorjs.github.io/phosphor-signaling/api/interfaces/isignal.html#connect
https://github.com/phosphorjs/phosphor-signaling/blob/HEAD/src/index.ts#L38
