### ISSUE TITLE
Add support for default values

### ISSUE THREAD

**Issue by jasonswearingen** [sebastian-lenz/typedoc#103]
For my API's JSON input parameters, I use a Class instead of an Interface because I can supply default values for fields not supplied by the user.

When using TypeDoc, those default values are not included in the generated documentation.

Currently I can workaround this by pasing the defaults into the jsdoc description.  It would be very nice if Typedoc could do this automatically, perhaps using decorators to toggle this (when decorator support is added)

**Comment by jasonswearingen** [comment]
example class with default values:
```
/** My class can be passed to my API as JSON */
export class MyClass{
/** my argument, default value of 'foo' if not supplied by user */
  public arg1:string="foo";
}
```

**Comment by sebastian-lenz** [comment]
Hi Jason, this feature has already been requested, please see #83. With support for decorators default values will become more important as it might be a valuable information about the used decorators.
