### ISSUE TITLE
Add support for suppressing Types/Members

### ISSUE THREAD

**Issue by jasonswearingen** [sebastian-lenz/typedoc#104]
another thing potentially made easier with decorators:

Allow suppressing of a Type or a Member, so that it's documentation is not included in the output.

A naive example:
```
/** my class used internally */
@Doc({ignore:true})
export class A{
}

/** my class for public use */
export class B{
@Doc({ignore:true})
public _dbId:number;
}

```

**Comment by sebastian-lenz** [comment]
Hi Jason, you can use the ```@hidden``` comment tag to achieve this:
```
export class B {
    /**
     * @hidden
     */
    public _dbId:number;
}
```

As it ist common practice to tag documentation relevant things in the comments, I don't think it is a good idea to use decorators for this. Decorators also emit additional but undesired JavaScript code.

**Comment by jasonswearingen** [comment]
Thank you very much!  I just tried the ```@hidden``` and it works.
