### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by EisenbergEffect** [sebastian-lenz/typedoc#106]
Is there a way to have TypeDoc generate a JSON file with the data rather than generating a site?

**Comment by sebastian-lenz** [comment]
Hi Rob, you can specify the output file of the desired json file with the '''--json''' parameter. If you are rendering your docs with Node you can also invoke TypeDoc directly and access the data models, take a look at the included Grunt task to get an idea of how to do this.

**Comment by EisenbergEffect** [comment]
Cool. Thanks! I thought it was possible but didn't see any documentation to that effect. We will be digging in soon.
