### ISSUE TITLE
eat memory and does nothing

### ISSUE THREAD

**Issue by jackstrapp** [sebastian-lenz/typedoc#107]
Hi, i have a problem using typedoc. 
I've already used it on the same project before some updates but now it seems like typedoc's doing nothing but eating memory untill i kill the node process (it can grow over a GB). I don't know if i'm doing something wrong. If i use the  --excludeExternals  option it works but things are missing (even things not really Excternals ). 

Could it be a loop file reference in my project?

Please Help.

PS: typedoc is fantastic (was in my case).

**Comment by sebastian-lenz** [comment]
Hi, sorry for the long delay, has been quite busy here. Yes, this sounds like some kind of infinite loop. Is your project available on GitHub so I could test it myself?

**Comment by jackstrapp** [comment]
Hi, 
thanks for the reply. 

No my project isn't on github. 

I wanted to get more informations from typedoc and i found the --verbose option but it don't work. 
It says: 
C:\Users\***>typedoc --verbose --out C:\mydoc Path/to/The/Solution/Folder
Error: Unknown option: verbose
(i am currently running on version 0.3.4 of typedoc)

Am i missing something?

Does this option should give me the answer of what i am doing wrong ?
Thank you.

**Comment by sebastian-lenz** [comment]
The <code>--verbose</code> option is no longer available. Where did you find that argument documented? Thought I've removed all references to it.

I made some changes to TypeDoc and reintroduced the verbose mode. Could you please replace your version of <code>typedoc.js</code> somewhere in <code>node_modules/typedoc/bin/typedoc.js</code> with [this one](https://github.com/sebastian-lenz/typedoc/raw/master/bin/typedoc.js)? This one should give us some hints when run with <code>--verbose</code>.

**Comment by jackstrapp** [comment]
Sure! 
i'll try that and come back as soon as possible.

For the <code>--verbose</code> option, i found this options when i was reading typedoc's issues. But i found it in <a href="http://typedoc.io/guides/usage.html">this page</a> (at the end).

Hope this helps if it's an mistake :)

**Comment by jackstrapp** [comment]
Ok, i think i found the problem thanks to the <code>verbose</code> option! 
Typedoc is making a loop on this piece of code: 

            var onSuccess: any = function () { };
            var onError: any = function () { };
            var onFinally: any = function () { };

            var callbackReturn = {
                success: (success_callback: () => any) => {
                    onSuccess = success_callback;
                    return callbackReturn;
                },
                error: (error_callback: () => any) => {
                    onError = error_callback;
                    return callbackReturn;
                },
                finally: (finally_callback: () => any) => {
                    onFinally = finally_callback;
                    return callbackReturn;
                }
            }
This looks like an async promise object. I will clean this code but this might be interesting for you to see this since there is no real error in the code.


And that is what typedoc prints on the console: 

Visiting ←[34m__object←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (220:32)
Visiting ←[34m__object.success←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (220:34)
Visiting ←[34m__object.error←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (224:18)
Visiting ←[34m__type←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (225:39)
Visiting ←[34m__object←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (220:32)
Visiting ←[34m__object.success←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (220:34)
Visiting ←[34m__object.finally←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (228:18)
Visiting ←[34m__type←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (229:43)
Visiting ←[34m__object←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (220:32)
Visiting ←[34m__object.success←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (220:34)
Visiting ←[34m__object.finally←[0m
    in C:/MERCURY_WILD/MERCURY_WILD/DEV/WildLib/wild_main/scriptsts/utilisateur.ts (228:18)

**Comment by jackstrapp** [comment]
I corrected the code. Now it works properly.  I'm curious about the problem. If you have an answer, I would like to know what is the problem.   

Thank you for your help!

**Comment by sebastian-lenz** [comment]
Great, we have a starting point. Of course you should not have to change your code. I'll have a look at this.

**Comment by sebastian-lenz** [comment]
Okay, we have a loop caused by the callbacks returning the containing anonymous object literal. I've changed the converter so TypeDoc should not run into this issue anymore.

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM containing the fix.

**Comment by jackstrapp** [comment]
Great ! Thank you for the help. By the way, the verbose option is still on the page i gave you before. Is that normal ? 
 again thanks.

**Comment by sebastian-lenz** [comment]
So the new version is working now for you? That's good news.

I've left the documentation of the verbose argument on the page as the new version now contains the verbose mode again.
