### ISSUE TITLE
Non exported members show up in documentation

### ISSUE THREAD

**Issue by MatanBobi** [sebastian-lenz/typedoc#108]
Hey sebastian,
I saw this issue: https://github.com/sebastian-lenz/typedoc/issues/87,
Is there any progress about this issue? Is there a way to help?
Thanks,

**Comment by sebastian-lenz** [comment]
Hi! Did you try the <code>-excludeNotExported</code> argument? Is there a situation where it's not working?

**Comment by sebastian-lenz** [comment]
I'll close this issue as no further information has been given. Please feel free to open a new issue if you encounter any problems.
