### ISSUE TITLE
typedoc command line exit value 0 even when failed

### ISSUE THREAD

**Issue by schettino72** [sebastian-lenz/typedoc#110]
Usually programs exit with a value different than `0` to indicate an error occurred.

This is very important when integrating with other programs like Continuous Integration systems.

**Comment by sebastian-lenz** [comment]
Missed that one, thanks for the note. Next version should return error codes.

**Comment by schettino72** [comment]
Thanks for the quick reply. It worked well for the actual error I was getting but failed for my "simple test".

```
$typedoc --xxx
```

Still exit with `0` status.

**Comment by sebastian-lenz** [comment]
You are right, missed that one.

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM containing the fixes.
