### ISSUE TITLE
Unable to specify both --readme and --entryPoint

### ISSUE THREAD

**Issue by darrylring** [sebastian-lenz/typedoc#114]
If both a readme file and an entry point are specified, the readme is ignored and `index.html` is empty. `globals.html` contains the documentation for the specified entry point as expected.

If both `--readme` and `--entryPoint` options are specified, `index.html` should display the readme file while `globals.html` should display the entry point.

**Example**

In this example, `index.html` will contain no content, while `globals.html` will display "Doc for a."

Command:
```bash
$ typedoc --out doc --module commonjs --mode file --target es5 --readme README.md --entryPoint a index.ts
```

index.ts:
```typescript
/** Doc for a */
module a {
    /** Doc for b */
    module b {
        /** Doc for A */
        export class A {
        }

        /** Doc for B */
        export interface B {
        }

        /** Doc for C */
        export enum C {
        }
    }
}
```
README.md:
```markdown
This is README.md.
```

**Comment by darrylring** [comment]
It looks like `model` in `index.hbs` is the module if `--entryPoint` is specified or the global typedoc object if not.

**Comment by sebastian-lenz** [comment]
Hi Darryl, thanks for the report and your fix!

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM containing your fix.
