### ISSUE TITLE
Is there a way to generate docs in presence of TypeScript errors?

### ISSUE THREAD

**Issue by 3nsoft** [sebastian-lenz/typedoc#116]
Is there a way to generate docs in presence of TypeScript errors?
Sometimes, even often, it is needed to make docs for your team, even when code has a few compile-time glitches.

**Comment by sebastian-lenz** [comment]
Currently there is no such option, TypeDoc will stop if the compiler emits any errors. We could add an option to let you bypass this check, however I can't guarantee the generated docs will be correct as I don't know in which state the compiler leaves the generated symbols.

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM which allows you to specify the <code>--ignoreCompilerErrors</code> argument.

**Comment by 3nsoft** [comment]
Yes, this works through gulp-typescript. Thanks a lot.
