### ISSUE TITLE
API does not accept 'out' but it does accept 'json'

### ISSUE THREAD

**Issue by rogierschouten** [sebastian-lenz/typedoc#120]
Hi Sebastian,

I just programmed gulp-typedoc to use the API instead of the CLI. Something I noticed was that if you pass an options object to the Application constructor, and the options object contains an 'out' member, conversion will fail with "Unknown option 'out'".  This is because the OptionsParser.parseObject() function is called with a false argument at the end of Application.bootstrapWithOptions().

I can see why Application doesn't need the 'out' option, as one typically calls the generateDocs() with the 'out' oneself. Interestingly, the behavior for 'out' is different from 'json'.

I've worked around it by deleting the 'out' argument before calling the Application constructor, so this is just a heads-up to see if you really intended this.

BR,
Rogier

**Comment by sebastian-lenz** [comment]
Hi Rogier, nice to hear from you. You can see my reference implementation of a Grunt plugin [here](https://github.com/sebastian-lenz/typedoc/blob/master/tasks/typedoc.js) and I am doing exactly what you did, I delete the <code>out</code> and <code>json</code> property of the options object.

It's intended that you get an error if you pass either the <code>out</code> or the <code>json</code> option to the application constructor. Both options are only added to the options parser [here](https://github.com/sebastian-lenz/typedoc/blob/master/src/td/Options.ts#L228) if TypeDoc is run from the command line. So I'm irritated that you did didn't get an error when passing the <code>out</code> option.

**Comment by rogierschouten** [comment]
I guess you fixed this :)  I've been getting questions about the json option producing an error using gulp-typedoc haha. I've fixed it in the same way as with the out option. Thanks
