### ISSUE TITLE
Documentation should escape HTML tags.

### ISSUE THREAD

**Issue by bluong** [sebastian-lenz/typedoc#125]
Reference issue: https://github.com/palantir/plottable-website/issues/131

Essentially, when opening up our documentation page, we see this...
![screen shot 2015-07-27 at 2 27 09 am](https://cloud.githubusercontent.com/assets/1448299/8902687/8823f668-3407-11e5-99a7-dbb9c7d6bda2.png)

The reason this happens is because in our jsdoc we have an `<svg>` tag to talk about the function.  Since we don't want to render html with our jsdoc, we want the tags to be escaped from rendering.

**Comment by sebastian-lenz** [comment]
Hi, thank you for sharing this. Turning off HTML rendering and starting escaping tags would break many other documentations, comments in TypeDoc are always rendered as markdown and therefore can contain HTML tags.

However I understand your need, there might be things in the comments like internal discussions that should not be rendered to the docs. On the other hand JSDoc comments should contain the documentation of your functions, for internal discussions you could always open a second non-JSDoc comment - which would be the cleaner version.

```
/**
 * The functions documentation.
 * @param value
 */

/*
 * The functions discussion.
 */

function foo(value:number) {
}
```

Why are you using the <code>&lt;svg&gt;</code> tag, is this common practice? I couldn't find anything about it. The only reasonable solution I see right now is to add a new comment tag that will not be rendered, e.g. <code>@discussion</code> or <code>@remark</code>.

**Comment by bluong** [comment]
When we were writing the jsdoc for the relevant doc, we did not consider the fact that our doc will be rendered as markdown.  We just thought the strings would be rendered as text onto the html page.
