### ISSUE TITLE
Empty interface definitions are not checked properly

### ISSUE THREAD

**Issue by vtkalek** [sebastian-lenz/typedoc#126]
Hi,
I found that TypeDoc is falling with error message:

" interfaceReflection.children.forEach(function.....
TypeError: Cannot read property 'forEach' of undefined.... "

It happens when it runs on the definition of such type:

" ....
export interface Entity {
//No members
} 
.....
"

So there should be a check if interfaceReflection really has children, something like if(interfaceReflection.children)

Best regards, Alex

**Comment by sebastian-lenz** [comment]
Hi Alex, thank you for the report. I've included a fix for the problem.

**Comment by sgal** [comment]
Hi,

When this fix will be released and published to npm?

Thanks,
Sergey

**Comment by sebastian-lenz** [comment]
Hi Sergey, sorry for the long delay, has been a hot summer :wink: 

I'll publish v0.3.9 to NPM today.

**Comment by sgal** [comment]
Thank you very much!

**Comment by sebastian-lenz** [comment]
@sgal Please note that version v0.3.9 that I've published earlier today contains a bug when resolving <code>lib.d.ts</code>, I've published v0.3.10 right now containing a fix.

**Comment by sebastian-lenz** [comment]
This one should be fixed. Pleas feel free to open a new issue if you encounter any problems.
