### ISSUE TITLE
Unrelated files being deleted upon documentation rebuild

### ISSUE THREAD

**Issue by WasabiFan** [sebastian-lenz/typedoc#132]
I currently run TypeDoc and tell it to dump the generated docs into a `docs/` folder, which also happens to be a submodule in my repo. Every time I regenerate my docs, the `.git` file is deleted and I lose my submodule. Is there a way to either:
- Explicitly specify files that shouldn't be touched
- Make it not delete files that aren't HTML in the TypeDoc structure

**Comment by sebastian-lenz** [comment]
Hi. Sorry, currently TypeDoc simply empties the output folder completely.

**Comment by sebastian-lenz** [comment]
I just added a new command line option <code>--disableOutputCheck</code> which allows you to turn of the automatic removal of the output directory. Please note that when using this switch it is your task to prepare the output directory so you should include some custom clean up script before running TypeDoc.

**Comment by WasabiFan** [comment]
Thanks! I'll give it a shot.
