### ISSUE TITLE
TS 1.6 has moved d.ts files to /lib

### ISSUE THREAD

**Issue by sccolbert** [sebastian-lenz/typedoc#134]
`getDefaultLibFileName` assumes that the TS builtin `d.ts` files are in `bin`. In TS 1.6, they have been moved to `lib`.

https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#js-content-of-npm-package-is-moved-from-bin-to-lib-folder

**Comment by sccolbert** [comment]
I'm trying to update typedoc in my fork to get it to work with 1.6 - how are you generating the `tsc.d.ts` file you are using for the typescript api? There are some other compiler host methods which need to be implemented for 1.6 (i think)

**Comment by sccolbert** [comment]
I think I figured it out. Checkout typescript source into project dir and run the grunt task, right?

**Comment by sebastian-lenz** [comment]
Hi Chris, I see, you figured it out already. To update the TypeScript version TypeDoc runs with you have to:

1. Install the TypeScript submodule (TypeScript should be located in ./typescript/)
2. Switch the head of the TypeScript submodule to the desired branch (e.g. [release-1.5](https://github.com/Microsoft/TypeScript/tree/release-1.5)) or tag (e.g. [v1.6.0-beta](https://github.com/Microsoft/TypeScript/tree/v1.6.0-beta)
3. Run the grunt task <code>ts:typescript</code> to build the definition file for that release, file <code>./src/lib/typescript/tsc.d.ts</code> should be updated
4. Run grunt task <code>default</code> to rebuild TypeDoc

If you are lucky this is all that has to be done. As TypeDoc does not solely rely on the official public API sometime things break and we have to adjust some calls.

**Comment by sebastian-lenz** [comment]
I've updated TypeDoc to be compatible with TypeScript 1.6-beta.

**Comment by jpitz** [comment]
@sebastian-lenz : I'm still having issues with this at the most recent version.

```
Using TypeScript 1.6.0-beta from /path/to/project/node_modules/typedoc/node_modules/typescript/lib
Error: Cannot find global type 'Array'.
Error: Cannot find global type 'Boolean'.
Error: Cannot find global type 'Function'.
Error: Cannot find global type 'IArguments'.
Error: Cannot find global type 'Number'.
Error: Cannot find global type 'Object'.
Error: Cannot find global type 'RegExp'.
Error: Cannot find global type 'String'.
```

Currently, I'm at "typedoc": "^0.3.9" in my package.json and verified that the actual version that's resolving is 0.3.9.

**Comment by sebastian-lenz** [comment]
Hi Jeremy, that's odd. Are you using the <code>--noLib</code> option? Looks like TypeScript is not picking up <code>lib.d.ts</code>.

**Comment by jpitz** [comment]
Nope, I'm still using the lib.

**Comment by sccolbert** [comment]
@sebastian-lenz  @jpitz error is stemming from line 418 of Converter.ts. It needs to be updated to point to the new lib directory. I've updated that line in my fork:

https://github.com/phosphorjs/typedoc/commit/133b0c33e8cfe4de083876731d8c91363bc5fa80#diff-d97da0d0b428457ad2da70404d9ca960

**Comment by sebastian-lenz** [comment]
Damm, Chris wrote about this in the comments above and I just relied upon my test cases but due to speed considerations they don't load the default lib. I've pushed an updated version 0.3.10 to npm.

**Comment by sccolbert** [comment]
Cheers!

**Comment by sebastian-lenz** [comment]
Okay, I think this one is resolved. Please feel free to open a new issue if there are still any issues.

**Comment by jpitz** [comment]
Verified the new version works.  Thanks!
