### ISSUE TITLE
Clicking on search item produces a "\" [Back-Slash] instead of "/" [Forward-Slash]

### ISSUE THREAD

**Issue by electricessence** [sebastian-lenz/typedoc#139]
This breaks the experience.

**Comment by sebastian-lenz** [comment]
Hi @electricessence, sorry to hear that, this looks like a bug that I cannot reproduce. Could you give me some details on how to reproduce it?

**Comment by electricessence** [comment]
In my case, my modules/classes mostly render in the search.js as having "\\" instead of "/".
I'm on windows.

**Comment by electricessence** [comment]
https://github.com/electricessence/TypeScript.NET/blob/3260c354aa90c80b84aa8318e19a3597e4601250/documentation/assets/js/search.js

**Comment by electricessence** [comment]
If I search replace "\\\" with "/" it works fine.

**Comment by electricessence** [comment]
Added this to the end of my typedoc gulp task:
```javascript
		const SEARCH_FOLDER = 'documentation/assets/js';

		gulp
			.src([SEARCH_FOLDER + '/search.js'])
			.pipe(require('gulp-replace')("\\\\","/"))
			.pipe(gulp.dest(SEARCH_FOLDER));
```

**Comment by sebastian-lenz** [comment]
Hi @electricessence, thank you for giving some insights, the link to your documentation helped a lot. Seems like somebody (me) tried to build URLs using the Path.join() method resulting in URLs containing the directory separator of the current platform TypeDoc is running on. I've included a fix, should be on NPM soon.

**Comment by electricessence** [comment]
You rock man.  Thanks!

**Comment by sebastian-lenz** [comment]
Great to hear it works now, thanks!
