### ISSUE TITLE
typedoc should support tsx

### ISSUE THREAD

**Issue by stepancar** [sebastian-lenz/typedoc#147]
Hello! Thank you for this project!
Now, as i understand, typedoc not supported tsx files, which available in TypeScript 1.6.
Do you have any plans for support jsdocs in tsx?
Its key feature which people needs, because it will allow doc react components which will be reused.
Thank you!

**Comment by fomahaut** [comment]
+1 for this. `.tsx` support would be awesome!

**Comment by ImEugene** [comment]
+1

**Comment by mihalycz** [comment]
+1

**Comment by sebastian-lenz** [comment]
TypeDoc parses TSX without problems but we currently down include them when a folder is specified as source. I've included the <code>*.tsx</code> extension so TypeDoc will pick up and parse those files.

I'm not familiar with React, besides the including <code>*.tsx</code> files, are there any specialities we should show in the documents?

**Comment by stepancar** [comment]
@sebastian-lenz
As i anderstand, your [changes](https://github.com/sebastian-lenz/typedoc/commit/acd58dc313595b35ebd67f8f13bebbbf33425860) 
is not in npm. Can you push it to npm for testing? After i'll notify you about my experience with awesome typedoc and tsx.
Thank you!

**Comment by sebastian-lenz** [comment]
I'll publish a new release soon, let me check the open issues first.

**Comment by stepancar** [comment]
Thank you, I'll be waiting :)

**Comment by sebastian-lenz** [comment]
v0.3.12 is on NPM!

**Comment by stepancar** [comment]
@sebastian-lenz, thank you! It Works for .tsx
