### ISSUE TITLE
Non-exported variables shouldn't be documented...

### ISSUE THREAD

**Issue by electricessence** [sebastian-lenz/typedoc#150]
It's getting confusing seeing my local/internal variables/constants/functions documented. :(

These shouldn't be exposed to the consumer, or at least there should be a switch to turn these off.
Personally, they should not be exposed by default.  Only what get's exported should be documented.

**Comment by electricessence** [comment]
Ok sorry, now I see the checkbox in the UI.  But I still think it's weird that it's off by default or even that it's an option.  Can we have an option not to have the option? :P

**Comment by electricessence** [comment]
Ok I found it :(
--excludeNotExported

**Comment by sebastian-lenz** [comment]
Great, an issue that has resolved itself :wink:

**Comment by electricessence** [comment]
This behavior still is a bit weird.  Because of the checkbox at the top.
It should disappear when this flag is set.

**Comment by sebastian-lenz** [comment]
You are right, the checkbox makes no sense if the parameter is specified, I've adjusted the template.
