### ISSUE TITLE
Exclude functionality

### ISSUE THREAD

**Issue by ddramone** [sebastian-lenz/typedoc#152]
Hello Sebastian.

I don't get how `exclude` flag works, can you provide some example?

```js
gulp
        .src(["src/App.ts"])
        .pipe(typedoc({
            ...
            exclude: "src/Config/Odds/*.ts",
            mode: 'file',
            ...
        }));
```

For this example it doesn't works. 
I want to exclude all ts files in src/Config/Odds folder.
How this patter really works?

**Comment by sebastian-lenz** [comment]
Hi, the <code>--exclude</code> parameter only becomes relevant if you specify a whole folder as source. When specifying a folder as source TypeDoc will deep search for all <code>*.ts</code> files inside that folder and using the <code>--exclude</code> parameter one can remove scanned files.

As you are specifying explicit files as source (<code>src/App.ts</code>) the <code>--exclude</code> parameter will never be used by TypeDoc. If you wan't prevent specific files from being documented you should check out the <code>--externalPattern</code> and <code>--excludeExternals</code> parameters which can be used to achieve this.

```
gulp
        .src(["src/App.ts"])
        .pipe(typedoc({
            ...
            externalPattern: "src/Config/Odds/*.ts",
            excludeExternals: true,
            mode: 'file',
            ...
        }));
```

**Comment by ddramone** [comment]
Now its clear and works perfectly tho.
Thanks for advice

**Comment by ddramone** [comment]
@Landish
