### ISSUE TITLE
Option to output as JSON

### ISSUE THREAD

**Issue by jasonswearingen** [sebastian-lenz/typedoc#171]
Request the ability to add JSON output, so that the results can more easily be used in documentation / example apps.

**Comment by sebald** [comment]
You can already do this :) See https://github.com/sebastian-lenz/typedoc#arguments

**Comment by jasonswearingen** [comment]
oh wow, that's great!  Do you happen to know of any oss projects that consume the output?   I want to make an api demo site like this thing I made a couple years ago:  https://phantomjscloud.com/site/docs.html#/api#api

**Comment by sebald** [comment]
Sorry, but I do not know ay OSS project that uses typedoc.

**Comment by jasonswearingen** [comment]
ok thank you.    If I can make my new doc page customizable enough, I'll try releasing one.
