### ISSUE TITLE
Theming tutorial

### ISSUE THREAD

**Issue by Evgenus** [sebastian-lenz/typedoc#24]
I've tried to customize generated files and have found it very nontrivial. It will be very nice have some example/tutorial/howtos about adding stuff into templates. 

Some simple like adding [ribbon](https://github.com/blog/273-github-ribbons) for a start.

**Comment by harunurhan** [comment]
@sebastian-lenz  this is closed but I still couldn't found a tutorial for theming or an example custom theme?

**Comment by aciccarello** [comment]
@harunurhan Here's the updated link to the themes guide:
http://typedoc.org/guides/themes/

You can find the default themes here:
https://github.com/TypeStrong/typedoc-default-themes

**Comment by caroso1222** [comment]
In case it's useful to anyone, I wrote a small how-to guide to customize a Typedoc theme.
