### ISSUE TITLE
Add support for private functions

### ISSUE THREAD

**Issue by Evgenus** [sebastian-lenz/typedoc#25]
functions and other entities (interfaces, classes, variables). Yes, there is no private classes and functions in typescript. But it could be specified in comments with `@private` tag. It is widespread case for type definition of some javascript code to hint preferred way to use it.

![](http://i.gyazo.com/dd90a39a5300c7262d073574c2a52d65.png)

In example above `@private` tag was specified and displayed in function description but it has no effect on filtering.

**Comment by sebastian-lenz** [comment]
Starting with the next version 0.2.3 of TypeDoc you can change the access level of declarations using <code>@private</code> and <code>@protected</code>.
