### ISSUE TITLE
Generic type instantiation lost

### ISSUE THREAD

**Issue by JeroMiya** [sebastian-lenz/typedoc#32]
When referencing a generic type with a specific type instantiation, the documentation only shows the name of the generic type and not the specific types.

note: "A of B" means A leftBracket B rightBracket (formatting fail, sorry)
example:
interface ITest of T {
  field: T;
}

interface IFoo {
   specificTest: ITest of string;
}

For IFoo.specificTest, I would expect to see in the documentation that the type of specificTest is ITest  for T: string. Currently, all that is shown is that specificTest is an ITest.

Also, the generated documentation for ITest only indicates that ITest is generic in the type of field ("field: T in ITest of T"). It should show the generic type arguments at the top of the page for the interface.

**Comment by sebastian-lenz** [comment]
This should be fixed with version 0.2 which introduces better handling of generics.
