### ISSUE TITLE
Typedoc incompatible with typescript 1.1

### ISSUE THREAD

**Issue by stolfgang** [sebastian-lenz/typedoc#38]
unfortunately typedoc does not run with typescript 1.1.0, which was relaesed a few days ago. Currently you only get the following message:
> Could not find ´typescript.js´. Please install typescript, e.g. 'npm install typescript'

**Comment by bluong** [comment]
Is there development being made on having typedoc being compatible with TS1.3?  We were using typedoc and then after upgrading to 1.3, we realized that there wasn't compatibility for the upgrade.

**Comment by sebastian-lenz** [comment]
Sorry for the very, very long delay, I've been pretty busy lately. Yes, there is definitely a lot of work going on in the background to make TypeDoc compatible with TypeScript 1.3. You can see and try the current status in the branch [v0.2](https://github.com/sebastian-lenz/typedoc/tree/v0.2).

In version 0.2 the complete process of extracting data from the TypeScript compiler has been rewritten. TypeDoc 0.2 is fully compatible with TypeScript 1.3 and supports new features like the protected keyword and tuple types. Also the generic support has been greatly improved, generic parameters show up in the documentation, can be documented and will be resolved correctly when e.g. subclasses implement a generic class. And, last but not least, the documentation generation is a lot faster now thanks to the improved compiler speed.

 However, this version is not finished yet. There are still several issues regarding the template rendering that have to be resolved. But we are near a beta release.

**Comment by bluong** [comment]
Do you have an estimate of when the release is?

**Comment by sebastian-lenz** [comment]
I can't promise anything, I hope to release a beta version this month on NPM.

Feel free to try the current development version:
- Clone TypeDoc v0.2 from https://github.com/sebastian-lenz/typedoc.git
- Create a subdirectory named <code>node_modules</code> and clone https://github.com/sebastian-lenz/typedoc-default-themes.git into <code>typedoc-default-themes</code>
- Return to the TypeDoc directory and use NPM to install the other dependencies <code>npm install</code>

**Comment by bluong** [comment]
I believe I tried the above and right now I'm running into an error module.js:340
    throw err;
          ^
Error: Cannot find module 'progress'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at td (/Users/bluong/git/typedoc/bin/typedoc.js:19:22)
    at Object.<anonymous> (/Users/bluong/git/typedoc/bin/typedoc.js:33:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by sebastian-lenz** [comment]
That's basically a good sign, "progress" is a new dependency of v0.2. It's correctly listed in the module info file. Did you install the dependencies of TypeDoc? There should be a folder "progress" in node_modules after that.

**Comment by bluong** [comment]
Yeah, I got the documentation to run now, however I'm now getting files like

docs/modules/**directoryInfo**.file.html

instead of what it was before with

docs/modules/file.html

**Comment by sebastian-lenz** [comment]
That is, of course, not intended. But, as I said, this version is not finished yet. Please feel free to open an issue if you mention any undesired behaviours.

**Comment by sebastian-lenz** [comment]
Microsoft has released TypeScript 1.4 with cool new features and TypeDoc still sticks to v1.0, that's annoying. Although I'm not feeling super happy with this decision, I've just published version 0.2 of TypeDoc on NPM which is at least compatible with TypeScript 1.3.

**Comment by kamranayub** [comment]
Awesome work, this means we can start to adopt it for our project!

**Comment by sebastian-lenz** [comment]
TypeDoc 0.2.2 is now on NPM which is compatible with TypeScript 1.4.

**Comment by markvandenbrink** [comment]
Great news TypeDoc is now compatible with the latest TypeScript release. Thanks for all the hard work! Documentation generated by TypeDoc is beautiful and clear. Really like it!
