### ISSUE TITLE
static method

### ISSUE THREAD

**Issue by vclteam** [sebastian-lenz/typedoc#41]
dont u think that public static method should appers on other classes?

**Comment by jvilk** [comment]
@vclteam is right, and I had no idea this was the case! True for methods and fields. Nasty.

```
class A {
    // The static method
    static foo():string { return 'bar'; }
    static bar: string = "foo";
}

class B extends A {
    // Document foo here
}

console.log(B.foo());
console.log(B.bar);
```

Compiling/running:
```
$ tsc test.ts
$ node test.js
bar
foo
```

And this means that `B` has a separate, implicitly inherited `bar` field from `A`.

**Comment by sebastian-lenz** [comment]
Actually TypeDoc behaves like this since v.0.2, static fields and methods are now inherited and I've also added the corresponding icons.
