### ISSUE TITLE
Generate documentation for external modules

### ISSUE THREAD

**Issue by smoli** [sebastian-lenz/typedoc#43]
I love typedoc, atm it's missing one thing (I guess). My project is completely based on external modules (amd in my case). I keep a comment at the top of every module file to document what the purpose of the module is. These comments don't show up in the generated documentation. 

Do I understand the documentation correctly that these comments only work for internal modules? Do you consider adding support for external modules?

**Comment by sebastian-lenz** [comment]
Hi smoli, nice to hear from you and sorry for the long delay. The support of module level comments is not limited to internal modules, they should also show up for external modules.

We are currently in the process of moving to TypeScript 1.3 and the process of resolving module comments already has been completely rewritten. It would be great if you could wait for the release of TypeDoc v0.2 and test it against your files again.

**Comment by smoli** [comment]
Hi Sebastian, thanks for the reply. I switched to internal modules in the meantime. That works perfectly. Thanks.
