### ISSUE TITLE
Future & How to Help

### ISSUE THREAD

**Issue by topherfangio** [sebastian-lenz/typedoc#47]
Hi there!

We just recently stared using TypeScript & TypeDoc and love the promise that it provides! Unfortunately, with all of the recent TypeScript changes, I understand that it is a bit difficult to keep up and make it work properly.

So two things:

1. Can you provide some brief thoughts on where things stand right now and the plans moving forward, and
2. Can you give some quick thoughts/notes on what the best way to assist would be?

We're definitely very invested in TypeScript and would love to have the level of documentation that TypeDoc will provide! We're developers and can definitely devote a bit of time if you can help guide us down the right path?

Thanks!

**Comment by paolopan83** [comment]
Support for new TypeScript versions would be very cool :)

**Comment by sebastian-lenz** [comment]
Hi Topher, nice to hear from you and sorry for the long delay. Regarding the current status I've just commented on issue #38. In brief: All work is currently concentrated on making TypeDoc compatible with TypeScript 1.1/1.3 (which has introduced an entirely new compiler infrastructure TypeDoc relies on) and all the work is going on on branch [v0.2](https://github.com/sebastian-lenz/typedoc/tree/v0.2). We are only a few steps away from a beta release.

If you want to contribute to this project you are more than welcome! As noted above, current development takes place in branch [v0.2](https://github.com/sebastian-lenz/typedoc/tree/v0.2). Starting with this version the templates will be placed in a separate module [typedoc-default-themes](https://github.com/sebastian-lenz/typedoc-default-themes) which currently must be downloaded and placed in the node_modules folder manually as I did not publish it to NPM yet. The idea behind this separation is a) making the project cleaner and b) open the project structure to make it possible for third-parties to write plugins.

The build process runs completely on Grunt, both projects provide a Gruntfile you can easily use to build and test the projects.

TypeDoc itself consists of two major parts: The **converter** invokes the TypeScript compiler, traverses the parsed statements and symbols and converts them into custom **models**. These models will be rendered by the **output** module using themes. The folders in the source directory reflect this structure. Both the converter and the renderer are event dispatchers and a series of plugins are attached to provide advanced functionality.
