### ISSUE TITLE
API Docs should include interfaces

### ISSUE THREAD

**Issue by brian428** [sebastian-lenz/typedoc#48]
Right now, classes which implement interfaces don't appear to include this information. Also, interfaces don't appear to list the classes that implement the interface.

**Comment by sebastian-lenz** [comment]
You are right, we should include this information.

**Comment by sebastian-lenz** [comment]
Changes are in the repository, will be available with TypeDoc 0.2.3

**Comment by thomas-delahaye** [comment]
Sorry to bring this issue up again. When we declare a class that implements an interface (using the `implements` keyword), we do not see the interface in the "implements" sections of the class.
Using TypeDoc v0.3.1.
Btw, is the "@inheritdoc" keyword supported when inheriting from an interface?

**Comment by sebastian-lenz** [comment]
Sorry, that's my fault, I've made the changes in the wrong file. <code>@ inheritdoc</code> is currently not supported, I've opened #78 as a new feature request.
