### ISSUE TITLE
More flexible / intelligent class links

### ISSUE THREAD

**Issue by brian428** [sebastian-lenz/typedoc#49]
Currently, it looks like Typedoc can only locate other classes (to link from a given class) if the other class is defined using a full path? E.g.:

Say I have a class in module `myApp.common.controllers` named `MyController`, and it has a method with a return type for `myApp.common.core.SomeBaseClass`. It looks like Typedoc will only pick up the external type link for the interface if the type is declared as `myApp.common.core.SomeBaseClass`. However, TSC is smart enough to compile correctly if the type is declared as just `core.SomeBaseClass`, since both classes are in the same parent module `myApp.common`.

I'm not sure how Typedoc actually does things (does it actually use the compiler? Or is it simply parsing the text of the files?). Either way, it would be nice if Typedoc could handle this. Obviously, the "abbreviated" paths are much shorter, as well as being more flexible (the parent modules could be changed without needing to update all the module paths).

Most likely this isn't a high priority item, but as I said, it would be nice if Typedoc could handle this.

**Comment by sebastian-lenz** [comment]
Hi Brian. TypeDoc completely relies on the TypeScript compiler, it does in no way parse your source files itself but extracts statements and symbols from the internal compiler data structures directly. I'm not aware of the problem you a describing, how did you invoke the compiler?

My guess is that you provide individual source files as entry points for the documentation. TypeDoc will mark other linked files as being "external" and won't create documentation for them by default. Did you use the <code>--excludeExternals</code> command line switch? If so, try to remove it.

**Comment by brian428** [comment]
OK, I think the issue was actually that I wasn't specifying --includeDeclarations! doh. Thanks for the great tool!

**Comment by sebastian-lenz** [comment]
Hey, thank you for your response!
