### ISSUE TITLE
Typescript 1.4 Type Alias hyperlinks

### ISSUE THREAD

**Issue by Mudhoax** [sebastian-lenz/typedoc#57]
It would be nice if the use of type aliases were linked to the definition of said alias.

e.g:

    export type Callback = <T>(val: T, index: number, arr: Array<T>): any;

    public someFunction<T>(arr: Array<T>, callback: Callback): any {
        ...
    }

The resulting documentation will specify the callback as type 'Callback', but not create a hyperlink to quickly view the type declaration.

**Comment by sebastian-lenz** [comment]
Hi Mudhoax, thank you for reporting this. Just looked into this, seems like we've tried to resolve the type alias to early. I guess <code>someFunction</code> is defined inside a class. Classes are reflected prior to type aliases which should have caused this error.

**Comment by Mudhoax** [comment]
Works now. Thanks!
