### ISSUE TITLE
Generic Type documentation

### ISSUE THREAD

**Issue by Mudhoax** [sebastian-lenz/typedoc#58]
Is there a better way to comment on a generic type declaration?

    /**
     * Some function that does something.
     * @param T The item type
     * @param a The item
     */
    public someFunction<T>(a: T): void {
        ...
    }

At the moment we are treating T as a @param, which seems to generate the correct documentation; it doesn't sit too well with me however lol.

**Comment by sebastian-lenz** [comment]
Yes, currently this is the only way to comment a type parameter. I have to admit this was a quick and dirty one. Any suggestions for a better tag? Maybe like this:

```
/**
 * Some function that does something.
 * @type T The item type
 * @param a The item
 */
public someFunction<T>(a: T): void {
    ...
}
```

**Comment by Mudhoax** [comment]
I wouldn't mind having the @type tag.

**Comment by sebastian-lenz** [comment]
Just asked Google, <code>@type</code> is used to annotate variables, see http://usejsdoc.org/tags-type.html. Maybe we should use another tag to avoid irritations. In this [discussion](http://stackoverflow.com/questions/2015972/is-there-a-javadoc-tag-for-documentating-generic-type-parameters) they tend to use the form <code>@param &lt;T&gt;</code>. I tend to add support for
- <code>@param T</code>
- <code>@param &lt;T&gt;</code>
- <code>@typeparam T</code>
