### ISSUE TITLE
Internal links in documentation

### ISSUE THREAD

**Issue by Mudhoax** [sebastian-lenz/typedoc#59]
Is there any way of declaring an internal reference to a part of the documentation via a comment block.

e.g.

    /**
     * Some function that does something. Also see {@link someOtherFunction}.
     */
    public someFunction(): void {
        ...
    }

**Comment by awerlang** [comment]
At typedoc.io it is said you can use double angle brackets, but I didn't manage to make it work.

**Comment by sebastian-lenz** [comment]
You should be able to create an internal link like this:

```
/**
 * Some function that does something. Also see [[someOtherFunction]].
 */
public someFunction(): void {
    ...
}
```

If it doesn't work for you it would be great if you could share the source code so I can have a look at this one.

**Comment by awerlang** [comment]
It is working for same class members and to link to another class.

How to link to another class' member?

```
interface Entity {
   id: number;
}
```

```
class EntityService {
    /*
     * @param id   see [[Entity.id]]
     */
    get(id: number) {...}
}
```

**Comment by sebastian-lenz** [comment]
Yes, this is the intended way. I've created a test case and noticed that the text gets linked to a wrong target. Do you see the same effect or does the text gets not linked for you at all?

**Comment by awerlang** [comment]
Text becomes a link to `\undefined`

**Comment by sebastian-lenz** [comment]
I've included two small bugfixes in 0.2.3, do the links work now?

**Comment by awerlang** [comment]
It is working now! Thanks!

**Comment by Mudhoax** [comment]
I can confirm that this now works as expected. Thanks for looking into this :+1:

**Comment by sebastian-lenz** [comment]
Great, thank you for testing it!

**Comment by janispritzkau** [comment]
How would I declare a reference to a static and a instance member? I've tried `[[Class:method]]` `[[Class::method]]` `[[Class#method]]`. If there's a static and instance method with the same name, `[[Class.method]]` creates a link to the static method.
