### ISSUE TITLE
How to hide a class member.

### ISSUE THREAD

**Issue by awerlang** [sebastian-lenz/typedoc#60]
Is it possible to hide a method from a class? It needs to be public because it implements an interface, but it doesn't make sense to call it directly. Think of explicit interface implementation in C#.

**Comment by sebastian-lenz** [comment]
Hi André, nice to hear from you. Your request seems somehow related to #25. Could we resolve your problem by enabling you to manually make the member to appear as private (e.g. by adding <code>@private</code> to the comment) in the documentation?

**Comment by awerlang** [comment]
Hi Sebastian

That's exactly what I'm looking for, it would be nice indeed. I'm closing this one then.

Thank you

PS: for the moment, I'm marking that member as `private` and casting to `any`. But then I loose type checking.

**Comment by sebastian-lenz** [comment]
Starting with the next version 0.2.3 of TypeDoc you can change the access level of declarations using <code>@private</code> and <code>@protected</code>.
