### ISSUE TITLE
No documentation for internal modules (0.2.3)

### ISSUE THREAD

**Issue by h-o-b** [sebastian-lenz/typedoc#61]
I just did the upgrade to TypeDoc 0.2.3 (from 0.1.x somewhere) and do not get any documentation for the contents of internal modules anymore, the index of "External module hello" is empty. Anything I might be doing wrong? When changed to an external module and --module set to commonjs, the documentation is nicely generated.

Sample Code (hello.ts):

```javascript
module hello {
  /**
   * Say hello
   */
  export function sayHello() {
  }
}
```

Command to build documentation:

`typedoc --out ... --mode modules --target es5 hello.ts`

Thanks for the great tool, btw.

**Comment by sebastian-lenz** [comment]
Hi, nice to hear from you. I've testes your code and it is working for me, I see the "hello" module containing the module hello and the function as expected.

Did you turn on "only activated" in the toolbar? As the <code>module hello</code> is not exported it will not show up.

**Comment by h-o-b** [comment]
Hi Sebastian

Oops, thank you, silly me.

However, I tend to disagree with respect to non-exportedness of top-level internal modules in typescript "no module" mode.

When using typescript with no module system selected, it is not possible to define top-level modules as exported. So IMHO there is no language means to specify these modules as exported, they by default just are exported.

So could you switch the default for top level modules in this mode to exported?

Best
Hannes

**Comment by sebastian-lenz** [comment]
Okay, I'm with you. In no module mode top level modules should be seen as exported.
