### ISSUE TITLE
Support @private for modules

### ISSUE THREAD

**Issue by h-o-b** [sebastian-lenz/typedoc#62]
Would it be possible to support the @private or similar annoation also for modules? I do have the case where some utility functionality should only be accessible from my own code, but of course to be able to access it from outside I have to exported them but do not want to show them in the docu.

Current workaround is to mark all the exposed functionality with @private, but this is tedious and the module itself still shows up.

**Comment by sebastian-lenz** [comment]
This has a lot of implications. Is everything inside a private module private? Also a class with public properties? We actually already have this problem as a class can now be marked as private.

So what would you think of a <code>@hidden</code> tag that would remove the marked symbols from the documentation?

**Comment by h-o-b** [comment]
That would be great.
And yes, in my opinion/case, if a module is hidden/private, all its features by definition are hidden as well.

**Comment by sebastian-lenz** [comment]
I've added the <code>@hidden</code> tag so we can exclude individual symbols from the documentation. You can now also mark modules with <code>@private</code>. This will however not mark all children as being private, I currently see no point in doing so. Seems to confusing to me.

**Comment by Landish** [comment]
Is it possible to hide parameters, that are only created with `constructor`?

```ts
class Example {

/***
 * Name Param - this will be hidden without a problem...
 * @hidden
 */
private name:string;

/***
 * @param name
 * @param age  - how to hide this param? 
 */
constructor(private name:string, private age:number){}
...
```

In the example above, how can I hide the `age` parameter, without creating it like the `name` param? 
I tried to ```@hidden param age``` but it didn't work.

**Comment by sebastian-lenz** [comment]
No, sorry there is no way to hide this member.

**Comment by iveetoo** [comment]
@sebastian-lenz can you add the `@hidden` tag in the TypeDoc documentation, because I'm sure there other people searching for this feature.

**Comment by aciccarello** [comment]
@iveetoo This project is now mostly maintained by the community so someone will have to submit a PR to update the documentation. For those looking for a little more on `@private` see #25

#293 also added support for excluding private variables though I don't know if this affects the constructor.
