### ISSUE TITLE
Question about json output

### ISSUE THREAD

**Issue by upta** [sebastian-lenz/typedoc#64]
First off, great project!

I'm using the json output option when generating my docs and everything is going great, but I ran into one question/request.  When I have a parameter/property type it has a symbolID, e.g.

```
{
    "id": 312,
    "name": "testSvc",
    "kind": 32768,
    "kindString": "Parameter",
    "flags": { },
    "type": {
        "type": "reference",
        "name": "TestSvc",
        "symbolID": 14778
    }
}
```
However, it seems that my TestSvc class doesn't actually have it's symbolID as one of it's members, making it much harder for me to make the association between the property and the class for linking inside my documentation.

Am I missing something, or is the any chance we could get that property added? :)

Thanks!

**Comment by sebastian-lenz** [comment]
Hi, nice to hear from you. Did you upgrade to the latest version of TypeDoc? It should give you an "id" field instead of the "symbolID".

**Comment by upta** [comment]
Man, you're all over this stuff, I swear I just updated to the latest version like last week.  Didn't even think there would have been another update yet :)  Looks good so far, thanks much!

**Comment by sebastian-lenz** [comment]
It's great to hear that it is working for you now. JSON export is pretty new so please feel free to open another issue if you encounter other problems.
