### ISSUE TITLE
Generics issue in json output

### ISSUE THREAD

**Issue by upta** [sebastian-lenz/typedoc#65]
Hey Sebastian,

I'm running into this same issue as #55 in the json file (this time I double checked and I have the npm 0.2.3 version ;) When I generate the whole docs instead of just the json file, the type params show up correctly.

Let me know if you need me to send you samples of what I'm seeing, thanks!

**Comment by sebastian-lenz** [comment]
My fault, I forgot to add the type parameters to the json output, they only show up in the rendered templates. I'll add them to the json output. Thanks for reporting this!

**Comment by upta** [comment]
Thanks for looking into it!
