### ISSUE TITLE
TypeError: Cannot read property 'elementTypes' of undefined

### ISSUE THREAD

**Issue by jvilk** [sebastian-lenz/typedoc#67]
It's great to finally see an actively maintained documentation generator for TypeScript! But I tried running typedoc on my project, [doppio](https://github.com/plasma-umass/doppio) on its `new-objects` branch, and it failed:

```
$ typedoc --out doc/ --mode file --module commonjs --target ES3 src/

Using TypeScript 1.4.1 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/bin

/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1297
                if (node.elementTypes) {
                        ^
TypeError: Cannot read property 'elementTypes' of undefined
    at extractTupleType (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1297:25)
    at extractType (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1271:28)
    at visitVariableDeclaration (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1768:41)
    at visit (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1499:32)
    at /usr/local/lib/node_modules/typedoc/bin/typedoc.js:1928:25
    at Array.forEach (native)
    at visitObjectLiteral (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1927:37)
    at visitVariableDeclaration (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1760:37)
    at visit (/usr/local/lib/node_modules/typedoc/bin/typedoc.js:1499:32)
    at /usr/local/lib/node_modules/typedoc/bin/typedoc.js:1928:25
```

Here's what you can do to reproduce the error (note: will take awhile due to repository size; build time is slow the first time because it needs to grab and extract a large file):
```
git clone https://github.com/plasma-umass/doppio
cd doppio
git checkout new-objects
bower install
npm install
grunt dev-cli
typedoc --out doc/ --mode file --module commonjs --target ES3 src/
```

Note that the `grunt dev-cli` step is required to generate `includes/JVMTypes.d.ts`, which is an 8MB declaration file containing TypeScript interface files for JVM objects (you'll notice the build system will first do a build that fails to typecheck due to the missing declarations -- required for bootstrapping :) ).

Let me know if there are any options I might be missing! Hopefully we can get typedoc working as beautifully on this new branch as it does on the master branch.

**Comment by sebastian-lenz** [comment]
Hi jvilk, nice to hear from you. I've checked the error location and found a trivial error. However I can currently not check it against you project as I'm not able to install it. On Windows the execSync dependency fails and on my Mac I cannot run the javac task. Would you mind to share your <code>JVMTypes.d.ts</code> with me?

**Comment by jvilk** [comment]
> On Windows the execSync dependency fails and on my Mac I cannot run the javac task.

Ahh yeah, the dreaded outdated `execSync` package! They've yet to accept my PR fixing the issue...

I believe [this version](https://gist.github.com/jvilk/39354703e0e5d150fe37) is up-to-date; let me know if it fails to compile!

**Comment by sebastian-lenz** [comment]
Thank you for sharing this one with me. I've tested the fix against your project and it seems to work right now. Well, as far as I can tell as doppio looks like a massive project. Kudos!

**Comment by jvilk** [comment]
Thanks! It's bigger than the average JS project, and I'm hoping to improve the internal documentation so it looks nice in typedoc-generated documentation. :smile: 

I look forward to the next release w/ the fix!

**Comment by jvilk** [comment]
Hey @sebastian-lenz, when are you planning to make a release with this fix?

**Comment by sebastian-lenz** [comment]
:tada: 

v0.3 is now on available on npm.

**Comment by jvilk** [comment]
And it works! Thanks!

**Comment by sebastian-lenz** [comment]
Great to hear. Thanks!
