### ISSUE TITLE
Generating docs from DefinitelyTyped type definitions?

### ISSUE THREAD

**Issue by Bartvds** [sebastian-lenz/typedoc#7]
Have you ever thought about using typedoc to generate documentation from type definitions?

I collaborate on DefinitelyTyped organisation and since we're sitting on this huge wealth of information we have this vague idea to generate documentation from all the type definitions.

I tried it with the typedoc commandline tool but it didn't work out-of-the-box.

If you'd feel like pursuing this we could put the output on http://definitelytyped.org website: we have automated builds and stuff and are looking at some webhooks so it could be very cool.

**Comment by jvilk** [comment]
@Bartvds nice! Looks like my effort in completely documenting Microsoft-Live-Connect resulted in some nice documentation (although a lot of the sidebar stuff is from pulled-in dependencies):

http://definitelytyped.org/docs/microsoft-live-connect--microsoft-live-connect/interfaces/microsoft.live.api.html
