### ISSUE TITLE
Support for ECMAScript 6

### ISSUE THREAD

**Issue by henkkuli** [sebastian-lenz/typedoc#72]
Hi!

The current TypeDoc doesn't support ES6 target even though TypeScript supports it. I think support should be added.

Here is an example code which does compile but not generate docs.
```typescript
/**
 * Offers functionality for loading files.
 */
class Loader {
    /**
     * Loads asynchronously file.
     * @param url The url of the file to be loaded.
     * @returns Promise of file.
     */
    loadDeferred(url: string): Promise<string> {
        return new Promise<string>((resolve: (value: string) => void, reject: (reason: any) => void) => {
            // ... load file here ...
        });
    }
}
```

If I understand right TypeScript compiler must just be told to use the new default lib filename. This can be done by changing the [CompilerHost's getDefaultLibFilename](https://github.com/sebastian-lenz/typedoc/blob/master/src/td/converter/Converter.ts#L1133) to:
```typescript
 getDefaultLibFilename: () => Path.join(ts.getDirectoryPath(ts.normalizePath(td.tsPath)), 'bin', options.target === ts.ScriptTarget.ES6 ? 'lib.es6.d.ts' : 'lib.d.ts')
```
This is basically the same as [grunt-typescript uses](https://github.com/k-maru/grunt-typescript/blob/master/src/host.ts#L231).

**Comment by sebastian-lenz** [comment]
Thanks, I haven't been aware of this change. Next version should include the fix.
