### ISSUE TITLE
Include/Exclude only some declarations.

### ISSUE THREAD

**Issue by florentpoujol** [sebastian-lenz/typedoc#73]
Hey ! 

One of my project reference two d.ts files, one I want in the doc, the other I don't want (because it's the whole node's declaration...).
Is there a way to do that right now ?
If not, that could be a really nice features to have, imo.

**Comment by sebastian-lenz** [comment]
Hi Florent, nice to hear from you. You can use the <code>--externalPattern</code> argument to achieve something like that. This option allows you to specify a pattern (parsed using minimatch, same as grunt uses, see https://github.com/isaacs/minimatch for details) that marks files a being external. You can exclude external files by specifying the the <code>--excludeExternals</code> flag.

**Comment by florentpoujol** [comment]
Alright, so after a lot of trials with the patterns, I was indeed able to exclude one declaration file from being documented !

Just for reference, my cmd line looks like this: 
`typedoc --out docs/ api/ [...] --includeDeclarations --excludeExternals --externalPattern **/*node*`
The pattern exclude the file which name contains "node" in the api/ folder.

Great job on typedoc by the way, really useful stuff, and the default themes are nice.
Many thanks !

**Comment by sebastian-lenz** [comment]
Thank you very much, great to hear!
