### ISSUE TITLE
typedoc: raises "TypeError: Cannot call method 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by pellekrogholt** [sebastian-lenz/typedoc#74]
nodejs version: v0.10.25
os: ubuntu 14.10
typedoc: 0.2.3 (also tried with master)

I do:

    $ ./node_modules/typedoc/bin/typedoc --help

    /my-project/node_modules/typedoc/bin/typedoc.js:259
                    _this.arguments[parameter.name.toLowerCase()] = parameter;
                                                   ^
    TypeError: Cannot call method 'toLowerCase' of undefined
        at /my-project/node_modules/typedoc/bin/typedoc.js:259:48
        at Array.forEach (native)
        at OptionsParser.addParameter (/my-project/node_modules/typedoc/bin/typedoc.js:256:24)
        at Application.runFromCommandline (/my-project/node_modules/typedoc/bin/typedoc.js:880:33)
        at Object.<anonymous> (/my-project/node_modules/typedoc/bin/typedoc:5:5)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
    
typedoc says it supports nodejs 0.10 and up

    https://github.com/sebastian-lenz/typedoc/blob/c8b15913032e2ceb9e3ffecc549dc40e074139c3/package.json#L28

I also tried with v0.12.0 and here typedoc works.

**Comment by sebastian-lenz** [comment]
Hi Pelle, nice to hear from you. Yes, I run all tests for TypeDoc against Node v0.10 and it [seems to work](https://travis-ci.org/sebastian-lenz/typedoc) with that version. Locally I'm testing against Node v0.12 and didn't encounter any problems either. Also regarding the error posted above I don't think it is related to Node.

The stack trace above looks like taken with a version you've pulled from the master branch as it mentions class OptionsParser and I've just added that one a few days ago. However, the line numbers don't match the current version so I guess you are using an outdated and probably buggy development version. If you want to use the latest version maybe you could pull again from the repro and try again running TypeDoc.

If you've also encountered problems running the version currently on NPM I'm also interested in getting to know this error.

**Comment by sebastian-lenz** [comment]
Okay, I still cannot track your problem so I'm closing this issue right now. Please feel free to open another issue if you encounter any other problems with TypeDoc.
