### ISSUE TITLE
TypeScript highlighter outdated

### ISSUE THREAD

**Issue by awerlang** [sebastian-lenz/typedoc#76]
`MarkedPlugin.ts` is not in sync with highlight.js implementation. There are some new keywords, like `constructor`, that aren't recognized.

Wouldn't it be better to reuse highlight.js implementation?

Plunker demonstrating it works with highlight.js: http://plnkr.co/edit/knbdB6SEOJs91eWKfiGb?p=info

```ts
        /**
         * Referência para o serviço do CRUD específico;
         * 
         * ~~~ts
         * constructor (servicoDeCrudDaEntidade, record) {
         *     this.crudSvc = servicoDeCrudDaEntidade;
         *     this.currentRecord = record;
         * }
         * ~~~
         */
        protected crudSvc: App.Services.CrudBaseService<any>;
```

**Comment by sebastian-lenz** [comment]
When writing <code>MarkedPlugin.ts</code> highlight.js didn't contain a definition for TypeScript but now there is built-in support for [TypeScript](https://github.com/isagalaev/highlight.js/blob/master/src/languages/typescript.js). Thank you for noting that, I'll remove the custom language definition.
