### ISSUE TITLE
Add @inheritdoc support

### ISSUE THREAD

**Issue by sebastian-lenz** [sebastian-lenz/typedoc#78]
When implementing interfaces <code>@inheritdoc</code> could copy the comment of the interface to the implementation. See #48.

**Comment by LimeStreem** [comment]
Hello,I appreciate this awesome project!
But,I'm also the user waiting this new feature. I wonder this feature is definitely important for this project.
When will you complete to implement this feature? Or,Could I help you to implement this feature?

**Comment by sebastian-lenz** [comment]
I've added this feature right now, it will be available with the next version of TypeDoc. We will release a new version in pair with TypeScript 1.5.

I can't implement new features as fast as we all would wish. Bugfixes and making TypeDoc compatible with the latest version of TypeScript always takes precedence for me. As this is a freetime project these tasks already take a lot of the time I can invest into the project. However, this is an open source project, so everyone who feels a strong need of a certain feature can implement it. I'm always happy to accept a pull request!

**Comment by LimeStreem** [comment]
I appliciate you!:satisfied:
Now I'm trying to make an feature for atom-typescript to generate typedoc comments by short cut key and I will make pull request to this project.
https://github.com/TypeStrong/atom-typescript

I hope this contribution makes peoples who is related to your project motivated in future.
