### ISSUE TITLE
Small bug: starting parameter comment with cross-link fails

### ISSUE THREAD

**Issue by kamranayub** [sebastian-lenz/typedoc#80]
Given:

```
* @param foo [[Entity]] is a foobar
```

Output is:

```
] is a foobar
```

in the docs.

**Comment by sebastian-lenz** [comment]
Thanks for the report. TypeDoc removes everything enclosed by "[]" and "{}" at the start of a parameter comment as other documentation generators use this pattern to annotate type definitions. The leftover <code>]</code> above is an error from this removal, furthermore the removal is not aware of double brackets.
