### ISSUE TITLE
Allow custom text for cross-links

### ISSUE THREAD

**Issue by kamranayub** [sebastian-lenz/typedoc#82]
It would be cool to allow changing the text shown in the hyperlink for a cross-link:

```
/**
 * See [[Event|how to use events]]
 */
```

My example uses a pipe delimiter to separate the first arg (entity) and second arg (text to display).

This would be useful for pluralization or shortening long paths.

**Comment by kamranayub** [comment]
Hey there, I tried using this with 0.3.2 and it doesn't work for this input:

```
[[Texture.asSprite|sprite from a Texture]]
```

It just leaves it raw.

![image](https://cloud.githubusercontent.com/assets/563819/6962985/2d31c92e-d93a-11e4-95d5-dc1ec91f7142.png)

**Comment by sebastian-lenz** [comment]
With v0.3.2 you mean the version on npm? The feature is on the master branch and not yet published to npm. You have to clone the current version from the repository or have to wait till v0.3.3 hits npm.

**Comment by kamranayub** [comment]
Ugh, I'm an idiot, GitHub releases page says "4 commits to master since this release", I thought it said "4 commits in this release" :-1: Sorry.

**Comment by kamranayub** [comment]
@sebastian-lenz Any idea when to expect 0.3.3?

**Comment by sebastian-lenz** [comment]
I've just published it to npm.
