### ISSUE TITLE
Property not showing in documentation

### ISSUE THREAD

**Issue by kamranayub** [sebastian-lenz/typedoc#85]
I have a property like this:

![image](https://cloud.githubusercontent.com/assets/563819/6967157/e8a0a66c-d95d-11e4-8f85-eec0b66df321.png)

And when I view the compiled docs, [it's missing](http://excaliburjs.com/docs/api/edge/classes/ex.actor.html). Any ideas? It works when I remove the default assignment.

**Comment by sebastian-lenz** [comment]
Well I can clearly see it.

![bildschirmfoto 2015-04-02 um 18 45 06](https://cloud.githubusercontent.com/assets/2273359/6968622/70329cde-d968-11e4-9e35-2ffec81a790d.png)

**Comment by kamranayub** [comment]
Ohhh, it's not in the properties section I guess. That was confusing!
