### ISSUE TITLE
Is there a way to ignore non-exported symbols?

### ISSUE THREAD

**Issue by sccolbert** [sebastian-lenz/typedoc#87]
I consider non-exported symbols (functions, vars, etc...) as part of the internal API, since those symbols are not reachable outside of the module. Is there a way to have those be ignored by the generator? I'd rather not have the private API symbols show up in the user API documentation.

Apologies if this is covered in the `typedoc.io` guide and I missed it somehow.

**Comment by sebastian-lenz** [comment]
Sorry, currently this is not possible, although it seems quite reasonably.

**Comment by sccolbert** [comment]
If you point me in the right direction, I'd be happy to work on a PR for this.

**Comment by sebastian-lenz** [comment]
Hi Chris, I've added a cli option and the opt-out code.

**Comment by sccolbert** [comment]
Awesome. Thank you!
