### ISSUE TITLE
Generic array literal types are not rendered correctly.

### ISSUE THREAD

**Issue by sccolbert** [sebastian-lenz/typedoc#88]
Sample function:

```
export
function sample<T>(a: T[], b: number[]): void { }
```

Rendered output
![sample](https://cloud.githubusercontent.com/assets/137289/7321505/9470128e-ea70-11e4-97c1-b8af6c6d2ce7.png)

Notice that the generic array type is missing the `[]` in the rendered output.

**Comment by sebastian-lenz** [comment]
Hi Chris, thank you for reporting this, I can reproduce this bug. Will be fixed in next release.

**Comment by sccolbert** [comment]
Awesome. Thank you!

**Comment by sebastian-lenz** [comment]
The new version on npm should include the fix. Can you confirm it is working now?

**Comment by sccolbert** [comment]
Works great now. Cheers!
https://phosphorjs.github.io/phosphor/modules/phosphor.collections.algorithm.html#binaryfind
