### ISSUE TITLE
Pages for classes that implement an interface do not mention the interface anywhere

### ISSUE THREAD

**Issue by rcchen** [sebastian-lenz/typedoc#89]
There should be something on class pages that indicates a method is an implementation of a method defined in its interface. Ideally, documentation on the interface propagates downwards to the class pages.

**Comment by sebastian-lenz** [comment]
TypeDoc currently only notes the implementation of an interface for the entire class, not on individual members, the demand seems reasonably to me.

The inheritance of interface comments has already been discussed in #48 and an issue #78 has been opened.

**Comment by sebastian-lenz** [comment]
TypeDoc now resolves interface implementations and links to the interface in docs. Will be available with next version.
