### ISSUE TITLE
Allow to specify an entry point to the documentation

### ISSUE THREAD

**Issue by sebastian-lenz** [sebastian-lenz/typedoc#90]
Currently TypeDoc always starts the documentation hierarchy in the global namespace, it should be possible to start the documentation within a specific module, everything outside this module will be discarded.

**Comment by marcusvetter** [comment]
Thanks for implementing the entry point. But how can i use it?
An interface of my project has the following path:

Globals "qc/event/IEvent" AT qc event IEvent

And i would like to enter the documentation with the package AT/qc.

Gruntfile: 
....
typedoc: {
            build: {
                options: {
                    module: 'commonjs',
                    out: 'mcdoc',
                    name: 'mcApi',
                    target: 'es5',
                    readme: 'README.md',
                    entryPoint: 'AS.qc'
....

Thanks a lot!
