### ISSUE TITLE
Generating warnings for undocumented elements

### ISSUE THREAD

**Issue by fforjan** [sebastian-lenz/typedoc#94]
Is there already an option to generate warnings when exported / public elements do not have the right information ?
Right informations could be missing documentations, invalid tags, parameters name not matching.

Happy to contribute if it's not in today and if you can give a starting point.

**Comment by sebastian-lenz** [comment]
This feature has been requested before, please see #50.

Currently this is not implemented although it should be easy to do. I wanted to implement this feature as a plugin so people who like to add this feature can install it optionally. If you would like to contribute this would also make the life for you much easier as you wouldn't have to dig around in TypeDoc. I could prepare a bare plugin to get you started if you would like to.

**Comment by fforjan** [comment]
Oups, sorry I quickly look for something similar but completely missed that one.
Yes, I was looking to start with plugin, so if you got a sample plugin, that would be good :)

**Comment by fforjan** [comment]
Closing that discussion
