### ISSUE TITLE
how are the Preview examples created?

### ISSUE THREAD

**Issue by jasonswearingen** [sebastian-lenz/typedoc#99]
Hi, I'm trying to see how the two examples were created, specifically what the source/inputs were for them:

http://typedoc.io/themes/default/
http://typedoc.io/themes/minimal/

can you please let me know the steps to create that?  (And it might be good to mention that on the parent page too: https://github.com/sebastian-lenz/typedoc (under "Preview")

**Comment by sebastian-lenz** [comment]
Hi, you can find the source of the two examples right here:
https://github.com/TypeDoc/themes

You can find the definition in the grunt file.

**Comment by jasonswearingen** [comment]
awesome, thank you so much!
